# -*- coding: utf-8 -*-
"""numero primos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13J2iRVJqyYmKPoJwhmStJS0j8RbU1frU
"""

def es_primo(num, n=2):
    if n >= num:
        return True
    elif num % n != 0:
        return es_primo(num, n + 1)
    else:
        return False

print("Los primeros 10 números primos son:")

primos = []
num = 1
while len(primos) < 10:
    if esprimo(num):
        primos.append(num)
    num += 1

print(primos)